;**** Timer **** 
TSCR1 EQU $46
TSCR2 EQU $4D
TIOS  EQU $40
TCTL1 EQU $48
TCTL2 EQU $49
TFLG1 EQU $4E
TIE   EQU $4C
TSCNT EQU $44
TC4	  EQU $58
TC1	  EQU $52
;***************

;*** PORTS **** 
DDRA  EQU $02
PORTA EQU $00
PORTB EQU $01
DDRB  EQU $03
PORTM EQU $0250
DDRM  EQU $0252
;**************

;**************INITIALIZATION*********

		LDAA #$FF			   ; Initialize port A for output
		STAA DDRA							  
		
;****************MAIN LOOP*************

TOP LDAA #$00
	STAA PORTA
	; IF LEFT BUTTON IS PRESSED JSR TO LEFT TURN FUNCTION
	  	 	  ; PB4 -> PB7 FLASH (ON 500 ms / OFF 500 ms)
	; IF RIGHT BUTTON IS PRESSED JSR TO RIGHT TURN FUNCTION
	  	 	  ; PB0 -> PB3 FLASH (ON 500 ms / off 500)
	; BRAKE LIGHT FUNCTION SHOULD BE AN INTERRUPT
	  		  ; PB0 -> PB7 ON UNTIL LEVER IS RELEASED
	BRA TOP
